package com.example.tasklist.models;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity representing a file attachment for a task.
 * Stores metadata about uploaded files including filename, size, and content type.
 */
@Entity
@Table(name = "task_attachments")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TaskAttachment {

    /**
     * Unique identifier for the attachment
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stored filename (unique, generated by system)
     */
    @Column(nullable = false)
    private String filename;

    /**
     * Original filename from user upload
     */
    @Column(nullable = false)
    private String originalFilename;

    /**
     * File size in bytes
     */
    @Column(nullable = false)
    private Long fileSize;

    /**
     * MIME type of the file (e.g., image/png, application/pdf)
     */
    @Column(nullable = false)
    private String contentType;

    /**
     * Timestamp when the file was uploaded
     */
    @Column(nullable = false)
    private LocalDateTime uploadedAt;

    /**
     * The task this attachment belongs to
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private Task task;

    /**
     * Pre-persist hook to set upload timestamp
     */
    @PrePersist
    protected void onCreate() {
        uploadedAt = LocalDateTime.now();
    }
}
